CREATE TABLE CONFIGURATION (
    REPO_PATH TEXT NOT NULL
);

CREATE TABLE BRANCHES (
    NAME TEXT PRIMARY KEY,
    LATEST_KNOWN_COMMIT TEXT,
    DESCRIPTION TEXT
);

CREATE TABLE BUILD_DEFINITIONS (
    NAME TEXT PRIMARY KEY,
    DESCRIPTION TEXT
);

CREATE TABLE STEPS (
    ID INT PRIMARY KEY,
    BUILD_NAME TEXT REFERENCES BUILDS(BUILD_NAME),
    STEP_ORDER INT NOT NULL,
    NAME TEXT NOT NULL,
    DESCRIPTION TEXT,
    COMMAND TEXT NOT NULL
);

CREATE TABLE BUILDS (
    NAME TEXT PRIMARY KEY,
    DESCRIPTION TEXT,
    BRANCH_NAME TEXT REFERENCES BRANCHES(BRANCH_NAME),
    BUILD_DEFINITION REFERENCES BUILD_DEFINITIONS(NAME)
)